export enum ActionTypes{
    
    GET_SINGLE_DATA_REQUEST ="GET_SINGLE_DATA_REUESTQ",
    GET_SINGLE_DATA_SUCCESS ="GET_SINGLE_DATA_SUCCESS",
    GET_SINGLE_DATA_ERROR="GET_SINGLE_DATA_ERROR",
    SET_SINGLE_DATA_SUCCESS ="SET_SINGLE_DATA_SUCCESS"
    }