export enum ActionTypes {
    GET_SINGLE_INTERVIEW_REQUEST = "GET_SINGLE_INTERVIEW_REQUEST",
    GET_SINGLE_INTERVIEW_SUCCESS = "GET_SINGLE_INTERVIEW_SUCCESS",
    GET_SINGLE_INTERVIEW_FAILURE = "GET_SINGLE_INTERVIEW_FAILURE",
}