export enum ActionTypes {
    CANCEL_SINGLE_INTERVIEW_REQUEST = "CANCEL_SINGLE_INTERVIEW_REQUEST",
    CANCEL_SINGLE_INTERVIEW_SUCCESS = "CANCEL_SINGLE_INTERVIEW_SUCCESS",
    CANCEL_SINGLE_INTERVIEW_FAILURE = "CANCEL_SINGLE_INTERVIEW_FAILURE",
}