export enum ActionTypes{
    GET_ADMIN_TYPE_LIST_REQUEST="GET_ADMIN_TYPE_LIST_REQUEST",
    GET_ADMIN_TYPE_LIST_SUCCESS="GET_ADMIN_TYPE_LIST_SUCCESS",
    GET_ADMIN_TYPE_LIST_FAILURE="GET_ADMIN_TYPE_LIST_FAILURE",
}