export enum ActionTypes{
    GET_ALL_ADMIN_LIST_BY_CATEGORY_REQUEST="GET_ALL_ADMIN_LIST_BY_CATEGORY_REQUEST",
    GET_ALL_ADMIN_LIST_BY_CATEGORY_SUCCESS="GET_ALL_ADMIN_LIST_BY_CATEGORY_SUCCESS",
    GET_ALL_ADMIN_LIST_BY_CATEGORY_FAILURE="GET_ALL_ADMIN_LIST_BY_CATEGORY_FAILURE"

}