export enum ActionTypes{
    GET_EVENTS_DATA_REQUEST ="GET_EVENTS_DATA_REQUEST",
    GET_EVENTS_DATA_SUCCESS ="GET_EVENTS_DATA_SUCCESS",
    GET_EVENTS_DATA_FAILURE="GET_EVENTS_DATA_FAILURE"
    }

    