export enum ActionTypes{
    GET_ALL_PAST_EVENTS_DATA_REQUEST ="GET_ALL_PAST_EVENTS_DATA_REQUEST",
    GET_ALL_PAST_EVENTS_DATA_SUCCESS ="GET_ALL_PAST_EVENTS_DATA_SUCCESS",
    GET_ALL_PAST_EVENTS_DATA_FAILURE="GET_ALL_PAST_EVENTS_DATA_FAILURE"
    }