export enum ActionTypes {
    CREATE_BULK_INTERVIEW_REQUEST = "CREATE_BULK_INTERVIEW_REQUEST",
    CREATE_BULK_INTERVIEW_SUCCESS = "CREATE_BULK_INTERVIEW_SUCCESS",
    CREATE_BULK_INTERVIEW_FAILURE = "CREATE_BULK_INTERVIEW_FAILURE",
}