export enum ActionTypes {
    UPDATE_SINGLE_INTERVIEW_REQUEST = "UPDATE_SINGLE_INTERVIEW_REQUEST",
    UPDATE_SINGLE_INTERVIEW_SUCCESS = "UPDATE_SINGLE_INTERVIEW_SUCCESS",
    UPDATE_SINGLE_INTERVIEW_FAILURE = "UPDATE_SINGLE_INTERVIEW_FAILURE",
}