export enum ActionTypes {
    CREATE_SINGLE_INTERVIEW_REQUEST = "CREATE_SINGLE_INTERVIEW_REQUEST",
    CREATE_SINGLE_INTERVIEW_SUCCESS = "CREATE_SINGLE_INTERVIEW_SUCCESS",
    CREATE_SINGLE_INTERVIEW_FAILURE = "CREATE_SINGLE_INTERVIEW_FAILURE",
}